# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
TARGET_WORDS_BIGENDIAN=yes
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES= /home/yzhao/work/xen_src/xen-4.5.0/tools/qemu-xen-traditional/gdb-xml/arm-core.xml /home/yzhao/work/xen_src/xen-4.5.0/tools/qemu-xen-traditional/gdb-xml/arm-vfp.xml /home/yzhao/work/xen_src/xen-4.5.0/tools/qemu-xen-traditional/gdb-xml/arm-vfp3.xml /home/yzhao/work/xen_src/xen-4.5.0/tools/qemu-xen-traditional/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
TARGET_HAS_BFLT=yes
